### ISSUE TITLE
[BUG] Player gets sent empty actionbar message when not over a road.

### ISSUE THREAD

**Issue by ajh123** [Abelkrijgtalles/mojang-maps#6]
When a player moves and they are not over a road they get sent an empty actionbar message, this results in any other actionbar messages being overridden.

The problematic code is:
https://github.com/Abelkrijgtalles/mojang-maps/blob/33a2a71ac839dbe8d7d5e441ca19252966df7d2b/src/main/java/nl/abelkrijgtalles/MojangMaps/listener/PlayerWalkListener.java#L46

A simple fix would be:
```java
String roadMsg = RoadUtil.getLocationMessage(p); // ask the RoadUtil for the location message
if (roadMsg != "") { // check if the message is not empty
       p.spigot().sendMessage(ChatMessageType.ACTION_BAR, new TextComponent(roadMsg)); // send the message like before
}
```

or you could read the action bar by using packets and let other actionbar messages take priority.

**Comment by Abelkrijgtalles** [comment]
Hi,
Thank you for your interest in Mojang Maps!
I will create a new hotfix for this

**Comment by Abelkrijgtalles** [comment]
I fixed it, so I will close it now
